const stacks = {
    html: "html5-plain-wordmark",
    css: "css3-plain-wordmark",
    js: "javascript-plain",
    react: "react-original-wordmark",
    git: "git-plain-wordmark",
    tailwind: "tailwindcss-original",
    redux: "redux-original",
    sass: "sass-original",
    nextjs: "nextjs-original-wordmark",
    github: "github-original-wordmark",
    npm: "npm-original-wordmark",
    postman: "postman-plain",
    vscode: "vscode-plain",
    php: "php-plain",
    mysql: "mysql-plain",
    python: "python-plain-wordmark",
    django: "django-plain",
    flask: "flask-original",
    sql: "sql-plain-wordmark",
    mongodb: "mongodb-plain-wordmark",
    nodejs: "nodejs-plain-wordmark",
    express: "express-original-wordmark",
    aws: "amazonwebservices-plain-wordmark",
    vercel: "vercel-plain",
    firebase: "firebase-plain-wordmark",
    figma: "figma-original",
    photoshop: "photoshop-plain",
    blender: "blender-plain-wordmark",
    unity: "unity-original-wordmark",
    unreal: "unrealengine-plain-wordmark",
}

export default stacks;